# -*- coding: utf-8 -*-
# This file is auto-generated by tools/generate_registry.py. Do not edit.

from modules.signal.analog_adc_afe import AdcCalibrationWindow
from modules.signal.opamp_circuit import OpampCalculatorWindow
from modules.signal.analog_pwm_tool import PwmToolWindow
from modules.power.battery_pack_bms import BatteryBmsWindow
from modules.signal.power_comm_tool import PowerCommTool
from modules.physical.comp_capacitor_life import CapacitorToolWindow
from modules.physical.comp_resistor_tool import ResistorToolWindow
from modules.control.control_digital_pid import DigitalControlWindow
from modules.control.control_loop_comp import LoopCompensationWindow
from modules.signal.digital_comms_bus import DigitalBusWindow
from modules.control.emc_filter_radiated import EmcCalculatorWindow
from modules.control.filter_passive_design import FilterDesignWindow
from modules.magnetics.mag_inductor_design import InductorDesignWindow
from modules.magnetics.mag_transformer_loss import TransformerDesignWindow
from modules.physical.pcb_impedance_heat import PcbCalculatorWindow
from modules.physical.phy_rc_discharge import RcChargeWindow
from modules.physical.phy_wire_busbar import WireCalculatorWindow
from modules.power.power_ac_three_phase import ThreePhaseCalculatorWindow
from modules.power.power_efficiency_budget import EfficiencyBudgetWindow
from modules.power.dcdc_basic import DcdcCalculatorWindow
from modules.power.power_dclink_ripple import DcLinkRippleWindow
from modules.power.power_device_driver import SwitchDeviceWindow
from modules.power.power_device_dpt import DoublePulseTestWindow
from modules.power.power_ldo_thermal import LdoThermalWindow
from modules.power.power_relay_driver import RelayDriverWindow
from modules.power.power_snubber_clamp import RcSnubberWindow
from modules.magnetics.power_topology_llc_pfc import AdvancedTopologiesWindow
from modules.control.power_load_transient import LoadTransientWindow
from modules.power.power_waveform_rms import WaveformCalculatorWindow
from modules.power.safe_creepage_clearance import SafetySpacingWindow
from modules.power.safe_input_protection import FuseCalculatorWindow
from modules.power.safe_tvs_zener import TvsZenerWindow
from modules.signal.sense_ct_shunt import CtDesignWindow
from modules.signal.sense_ntc_fitting import NtcCalculatorWindow
from modules.physical.theory_lc_reactance import LcBasicWindow
from modules.power.thermal_heatsink_steady import HeatsinkCalculatorWindow

REGISTRY = {
    'analog_adc': AdcCalibrationWindow,
    'analog_opamp': OpampCalculatorWindow,
    'analog_pwm': PwmToolWindow,
    'battery_pack': BatteryBmsWindow,
    'comm_powercomm': PowerCommTool,
    'comp_cap': CapacitorToolWindow,
    'comp_r_tool': ResistorToolWindow,
    'control_digital': DigitalControlWindow,
    'control_loop': LoopCompensationWindow,
    'digital_bus': DigitalBusWindow,
    'emc_calc': EmcCalculatorWindow,
    'filter_passive': FilterDesignWindow,
    'mag_inductor': InductorDesignWindow,
    'mag_transformer': TransformerDesignWindow,
    'pcb_tool': PcbCalculatorWindow,
    'phy_rc': RcChargeWindow,
    'phy_wire': WireCalculatorWindow,
    'power_ac_3ph': ThreePhaseCalculatorWindow,
    'power_budget': EfficiencyBudgetWindow,
    'power_dcdc': DcdcCalculatorWindow,
    'power_dclink': DcLinkRippleWindow,
    'power_device': SwitchDeviceWindow,
    'power_dpt': DoublePulseTestWindow,
    'power_ldo_th': LdoThermalWindow,
    'power_relay': RelayDriverWindow,
    'power_snubber': RcSnubberWindow,
    'power_topology': AdvancedTopologiesWindow,
    'power_transient': LoadTransientWindow,
    'power_waveform': WaveformCalculatorWindow,
    'safe_creepage': SafetySpacingWindow,
    'safe_fuse': FuseCalculatorWindow,
    'safe_tvs': TvsZenerWindow,
    'sense_ct': CtDesignWindow,
    'sense_ntc': NtcCalculatorWindow,
    'theory_lc': LcBasicWindow,
    'thermal_heatsink': HeatsinkCalculatorWindow,
}
