# tools/generate_registry.py

import importlib
import inspect
import os
import sys


SKIP_FILES = {"base_module.py", "static_registry.py"}


def _prepare_path(root_dir):
    paths = [root_dir]
    paths.extend(os.path.join(root_dir, "modules", folder) for folder in ["magnetics", "power", "control", "signal", "physical"])
    for path in reversed(paths):
        if path not in sys.path:
            sys.path.insert(0, path)


def _iter_module_names(modules_dir):
    for root, _, files in os.walk(modules_dir):
        for file_name in files:
            if not file_name.endswith(".py") or file_name.startswith("__") or file_name in SKIP_FILES:
                continue
            relative_path = os.path.relpath(os.path.join(root, file_name), modules_dir)
            module_parts = relative_path[:-3].replace(os.path.sep, ".")
            yield f"modules.{module_parts}"


def generate():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    modules_dir = os.path.join(root_dir, "modules")
    static_registry_path = os.path.join(modules_dir, "static_registry.py")

    _prepare_path(root_dir)

    from modules.base_module import BaseModule

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    print("Generating static module registry...")
    modules_found = {}

    for module_name in sorted(_iter_module_names(modules_dir)):
        try:
            mod = importlib.import_module(module_name)
            for name, obj in inspect.getmembers(mod, inspect.isclass):
                if obj.__module__ != mod.__name__:
                    continue
                if issubclass(obj, BaseModule) and obj is not BaseModule and obj.window_id:
                    modules_found[obj.window_id] = (module_name, name)
                    print(f"  found: {name} (ID: {obj.window_id})")
        except Exception as exc:
            print(f"  [Warning] failed to load {module_name}: {exc}")

    with open(static_registry_path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("# This file is auto-generated by tools/generate_registry.py. Do not edit.\n\n")

        for _, (module_name, class_name) in sorted(modules_found.items()):
            f.write(f"from {module_name} import {class_name}\n")

        f.write("\nREGISTRY = {\n")
        for window_id, (_, class_name) in sorted(modules_found.items()):
            f.write(f"    {window_id!r}: {class_name},\n")
        f.write("}\n")

    print(f"Static registry generated: {static_registry_path}")


if __name__ == "__main__":
    generate()
